/*

 COIN.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

unsigned char coins_tile_map[] =
{
  129,
};

/* Start of tile array. */
unsigned char coins_tile_set[] =
{
  0x00,0x7E,0x24,0xFF,0x28,0xFF,0x30,0xFF,
  0x30,0xFF,0x28,0xFF,0x24,0xFF,0x00,0x7E,
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00
};

/* End of COINS.C */
