
#ifndef SETTINGS_INCLUDE
#define SETTINGS_INCLUDE

#define FALL_SPEED 3
#define MOVE_SPEED 1
#define COIN_SPEED 2
#define TILE_HEIGHT 8
#define TILE_WIDTH 8
#define GAME_LENGTH_SECONDS 30
#define SCREEN_WIDTH 160
#define SCREEN_HEIGHT 144
#define COIN_COUNT 3

#endif